# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: berlinpixels
email: moritz@frontierpsychiatrist.de
description: > # this means to ignore newlines until "baseurl:"
  photos of berlin, cropped, pixelized, reduced in color
  in remembrance of the good old times
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://berlinpixels.com"

# Build settings
markdown: kramdown
